os: linux
dist: trusty
sudo: required

before_install:
  - wget https://swift.org/builds/development/ubuntu1404/swift-DEVELOPMENT-SNAPSHOT-2016-09-05-a/swift-DEVELOPMENT-SNAPSHOT-2016-09-05-a-ubuntu14.04.tar.gz 
  - tar xzvf swift-DEVELOPMENT-SNAPSHOT-2016-09-05-a-ubuntu14.04.tar.gz
  - export PATH=swift-DEVELOPMENT-SNAPSHOT-2016-09-05-a-ubuntu14.04/usr/bin:$PATH
  - sudo apt-get -y install clang libicu-dev libkqueue-dev libtool libcurl4-openssl-dev libbsd-dev libblocksruntime-dev mysql-server
  - git clone -b 9/05-migration https://github.com/IBM-Swift/todolist-tests Tests
  - sqlite3 todolist.sqlite < schema.sql
  
script:
  - swift build -Xswiftc -I/usr/local/include/mysql -Xlinker -L/usr/local/lib -Xcc -fblocks
  - swift test
